# Generated by Django 5.2.4 on 2026-01-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0002_shop_lat_shop_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
