# Generated by Django 5.2.4 on 2025-11-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0004_remove_post_content_remove_post_title_post_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
